#!/bin/bash

# Author: Ifiok
# Date: 23/10/2024

# test-file: Evaluate the status of a file
read -p "Please Enter filename: " FILE
# FILE=~/.bashrc
if [ -e "$FILE" ]; then
	if [ -f "$FILE" ]; then
		echo "$FILE: is a regular file"
	fi
	if [ -d "$FILE" ]; then
		echo "$FILE: is a directory"
	else
		echo "$FILE: is not a directory"
	fi
	if [ -r "$FILE" ]; then
		echo "$FILE: is readable"
	fi
	if [ -w "$FILE" ]; then
		echo "$FILE: is writable"
	fi
	if [ -x "$FILE" ]; then
		echo "$FILE: is executable"
	else
		echo "$FILE: is not executable"
	fi
else
	echo "$FILE does not exit"
	exit 1
fi

exit

